name: CI
on: [push]

jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .[tests]

      - name: Test with pytest
        run: |
          python -m pytest

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml] pycodestyle pylint

      - name: Run pycodestyle
        run: |
          pycodestyle --max-line-length=120 .

      - name: Run pylint
        if: success() || failure() # still run pylint if above checks fails
        run: |
          pylint ctakesclient/ scripts/* tests/

      - name: Run bandit
        if: success() || failure() # still run bandit if above checks fail
        run: |
          bandit -c pyproject.toml -r .
